### PR TITLE
Add throttle effect

### PR DESCRIPTION
**Pull request by tekktrik**
Adds a throttle effect for the dial, where the dial will randomly fluctuate around it's setpoint.  Also adds an example file for showing usage.

### CODE REVIEW

**Comment by tekktrik** [comment]
I also just realized that it may be possible to generalize this effect into a new library, so that it can be applied to other UI widgets, something like this:

```python
from displayio_dial import Dial
from displayio_effects import throttle_effect

my_dial = Dial(
    ....
)

throttle_effect.hook_throttle_effect(my_dial)

...

my_dial.value = 50
my_dial.throttle_effect = 5
my_dial.throttle_effect_move_rate = 0.1

while True:
    my_dial.throttle_update()
    display.refresh()
```

**Comment by FoamyGuy** [comment]
I like the idea of generalizing this idea of effects for displayio widgets into it's own library more than including specifically the throttle one in this library.

I do think it would be okay to include an example in this repo that shows how to do this, but the code that was added to `displayio_dial.py` here I think should instead live in it's own repo (ultimately alongside other possible effects for updating properties) like the one you've started over at https://github.com/tekktrik/CircuitPython_Org_DisplayIO_Effects.

Two things that I think may be worth considering to tweak are:

Maybe choose a different name for this effect. I see how visually it mimics a throttle on a vehicle when used on the dial like this. But with the effect more generalized it could be used to achieve different visual effects with other components that might not resemble a throttle. My thought would be to try to describe the type of rules that the effect uses to select the updated values so this one might be something like ClampedRandom or something because it chooses the next value randomly, but is clamped to a maximum possible amount to change per update.

In the example I don't think `display.refresh()` is needed inside the main loop. Auto refresh is on by default so user doesn't typically need to call `display.refresh()` unless they have explicitly disabled it. I noticed after removing it that the visual effect is a little more "jumpy" and not as smooth. (likely due to display.refresh() call consuming extra time when it is present). It can be slowed back down to make it smooth again either by adding a `time.sleep()` (or some other "waiting" mechanism) or just by lowering the `my_dial.throttle_effect_move_rate` I found that setting that to `0.01` instead of `0.1` smoothed the visual changes back out to looking pretty much the same as the original script. 

I don't think there is inherently broken due to calling `display.refresh()` but it does consume extra time and I am afraid if people find it in examples like this that they'll assume they need it in their own code when they usually don't.

**Comment by tekktrik** [comment]
I think both of those suggestions sound good!  I'll pick a more generalized name for the effect, as well as update the example to remove the refresh.  I may also tweak the values so that they are "rounder" (maybe use factors of 10 if needed). I'll get started on that!

**Comment by tekktrik** [comment]
Closing in favor of adding a new library for effects

**Pull request closed without merging**
